steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['clean','install','-Dmaven.test.skip=true']
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$_TAG_NAME', '--build-arg=JAR_FILE=target/*.jar', '.']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', $_SERVICE_NAME, '--image', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$_TAG_NAME', '--region', $_REGION]  
substitutions:
  _TAG_NAME: latest
  _IMAGE_NAME: helloworld
  _SERVICE_NAME: helloworld
  _REGION: us-central1
images:
  - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$_TAG_NAME